name: "Terraform Deploy EC2"

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      public_count:
        description: 'Instances in PUBLIC Subnet'
        required: true
        default: '1'
        type: choice
        options: ['0', '1', '2']
      private_count:
        description: 'Instances in PRIVATE Subnet'
        required: true
        default: '0'
        type: choice
        options: ['0', '1', '2']
      isolated_count:
        description: 'Instances in ISOLATED Subnet'
        required: true
        default: '0'
        type: choice
        options: ['0', '1', '2']

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_public_instance_count: ${{ github.event.inputs.public_count }}
          TF_VAR_private_instance_count: ${{ github.event.inputs.private_count }}
          TF_VAR_isolated_instance_count: ${{ github.event.inputs.isolated_count }}
          TF_VAR_subnet_public_id: ${{ secrets.SUBNET_PUBLIC_ID }}
          TF_VAR_subnet_private_id: ${{ secrets.SUBNET_PRIVATE_ID }}
          TF_VAR_subnet_isolated_id: ${{ secrets.SUBNET_ISOLATED_ID }}
          TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
        run: terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_public_instance_count: ${{ github.event.inputs.public_count }}
          TF_VAR_private_instance_count: ${{ github.event.inputs.private_count }}
          TF_VAR_isolated_instance_count: ${{ github.event.inputs.isolated_count }}
          TF_VAR_subnet_public_id: ${{ secrets.SUBNET_PUBLIC_ID }}
          TF_VAR_subnet_private_id: ${{ secrets.SUBNET_PRIVATE_ID }}
          TF_VAR_subnet_isolated_id: ${{ secrets.SUBNET_ISOLATED_ID }}
          TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
        run: terraform apply -auto-approve
