name: "Terraform Deploy EC2"

on:
  # push:
  #   branches:
  #     - main

  # 1. Configures the interactive UI menu for manual execution
  workflow_dispatch:
    inputs:
      instance_count:
        description: 'Choose the number of instances to deploy to the sandbox'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  
jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # 2. Passes the UI dropdown selection directly down to Terraform's variable
      - name: Terraform Plan
        env:
          TF_VAR_instance_count: ${{ github.event.inputs.instance_count }}
          TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
          TF_VAR_subnet_ids: '["${{ secrets.SUBNET_PUBLIC_ID }}", "${{ secrets.SUBNET_PRIVATE_ID }}", "${{ secrets.SUBNET_ISOLATED_ID }}"]'
        run: terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_instance_count: ${{ github.event.inputs.instance_count }}
          TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
          TF_VAR_subnet_ids: '["${{ secrets.SUBNET_PUBLIC_ID }}", "${{ secrets.SUBNET_PRIVATE_ID }}", "${{ secrets.SUBNET_ISOLATED_ID }}"]'
        run: terraform apply -auto-approve
